name:                treebot
version:             0.1.0.0
github:              "william42/treebot"
license:             BSD3
author:              "Will A Cadegan-Schlieper"
maintainer:          "wacs@covering.space"
copyright:           "Copyright (c) 2018- W.A.C-S."

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/william42/treebot#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- MonadRandom
- diagrams-lib
- diagrams-svg
- diagrams-rasterific
- diagrams-contrib
- Hastodon
- text
- dhall

library:
  source-dirs: src

executables:
  treebot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treebot

tests:
  treebot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - treebot
